[package]
name = "cim_decrypter"
version = "0.1.0"
authors = ["Bela Stoyan <bas@nyantec.com>"]
edition = "2018"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
libc = "*"
scan_fmt = "*"